import pandas as pd\n,
import numpy as np\n,
from sklearn import linear_model\n,
df=pd.read_csv('train_sep.csv', delimiter = ',',encoding= 'unicode_escape')\n,
df['day_temp'] = df.temp.shift(-24)\n,
df['grad_temp'] = df.temp.shift(72)\n,
#df['2day_temp'] = df.temp.shift(-48)\n,
X_test = df.tail(24)\n,
del X_test['day_temp']\n,
df = df.dropna()\n,
X_train = df\n,
y_train = X_train['day_temp']\n,
del X_train['day_temp']\n,
regressor = linear_model.LinearRegression()\n,
regressor.fit(X_train, y_train)\n,
prediction = regressor.predict(X_test)\n,
X_test['predict'] = np.array(prediction)\n,
X_test['predict'] = round(X_test['predict'],2)\n,
X_test